//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.14 at 10:18:10 PM CET 
//


package com.mcmiddleearth.plugins.dynamicbooks.jaxb;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.mcmiddleearth.plugins.dynamicbooks.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _XMLBookXMLPagesXMLPageX_QNAME = new QName("", "x");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.mcmiddleearth.plugins.dynamicbooks.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link XMLBook }
     * 
     */
    public XMLBook createXMLBook() {
        return new XMLBook();
    }

    /**
     * Create an instance of {@link XMLBook.XMLPages }
     * 
     */
    public XMLBook.XMLPages createXMLBookXMLPages() {
        return new XMLBook.XMLPages();
    }

    /**
     * Create an instance of {@link XMLBook.XMLPages.XMLPage }
     * 
     */
    public XMLBook.XMLPages.XMLPage createXMLBookXMLPagesXMLPage() {
        return new XMLBook.XMLPages.XMLPage();
    }

    /**
     * Create an instance of {@link XMLBook.XMLTemplates }
     * 
     */
    public XMLBook.XMLTemplates createXMLBookXMLTemplates() {
        return new XMLBook.XMLTemplates();
    }

    /**
     * Create an instance of {@link XMLTemplate }
     * 
     */
    public XMLTemplate createXMLTemplate() {
        return new XMLTemplate();
    }

    /**
     * Create an instance of {@link XMLBook.XMLPages.XMLPage.XMLX }
     * 
     */
    public XMLBook.XMLPages.XMLPage.XMLX createXMLBookXMLPagesXMLPageXMLX() {
        return new XMLBook.XMLPages.XMLPage.XMLX();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLBook.XMLPages.XMLPage.XMLX }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link XMLBook.XMLPages.XMLPage.XMLX }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "x", scope = XMLBook.XMLPages.XMLPage.class)
    public JAXBElement<XMLBook.XMLPages.XMLPage.XMLX> createXMLBookXMLPagesXMLPageX(XMLBook.XMLPages.XMLPage.XMLX value) {
        return new JAXBElement<XMLBook.XMLPages.XMLPage.XMLX>(_XMLBookXMLPagesXMLPageX_QNAME, XMLBook.XMLPages.XMLPage.XMLX.class, XMLBook.XMLPages.XMLPage.class, value);
    }

}
