//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.21 at 09:59:03 AM CET 
//


package com.mcmiddleearth.plugins.dynamicbooks.jaxb;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlMixed;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="permissions" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="give" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                   &lt;element name="open" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                   &lt;element name="giveremote" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                   &lt;element name="openremote" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="templates" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="template" type="{}template" maxOccurs="unbounded"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="page" maxOccurs="100"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="line" maxOccurs="14"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;choice maxOccurs="unbounded"&gt;
 *                             &lt;element name="tpl" maxOccurs="unbounded"&gt;
 *                               &lt;complexType&gt;
 *                                 &lt;simpleContent&gt;
 *                                   &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
 *                                     &lt;attribute name="ref" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                                     &lt;attribute name="arg1" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                                     &lt;attribute name="arg2" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                                     &lt;attribute name="arg3" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                                     &lt;attribute name="arg4" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                                     &lt;attribute name="arg5" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                                     &lt;attribute name="styles" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                                     &lt;attribute name="color" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                                     &lt;attribute name="auto-type" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                                     &lt;attribute name="page" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                                     &lt;attribute name="url" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                                     &lt;attribute name="hover-text" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                                     &lt;attribute name="execute" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                                     &lt;attribute name="open-book" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                                     &lt;attribute name="give-book" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                                   &lt;/extension&gt;
 *                                 &lt;/simpleContent&gt;
 *                               &lt;/complexType&gt;
 *                             &lt;/element&gt;
 *                             &lt;element name="obj" maxOccurs="unbounded"&gt;
 *                               &lt;complexType&gt;
 *                                 &lt;simpleContent&gt;
 *                                   &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
 *                                     &lt;attribute name="styles" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                                     &lt;attribute name="color" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                                     &lt;attribute name="auto-type" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                                     &lt;attribute name="page" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                                     &lt;attribute name="url" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                                     &lt;attribute name="hover-text" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                                     &lt;attribute name="execute" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                                     &lt;attribute name="open-book" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                                     &lt;attribute name="give-book" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                                   &lt;/extension&gt;
 *                                 &lt;/simpleContent&gt;
 *                               &lt;/complexType&gt;
 *                             &lt;/element&gt;
 *                           &lt;/choice&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *                 &lt;attribute name="ref" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="author" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "permissions",
    "templates",
    "page"
})
@XmlRootElement(name = "book")
public class XmlBook {

    protected XmlBook.XmlPermissions permissions;
    protected XmlBook.XmlTemplates templates;
    @XmlElement(required = true)
    protected List<XmlBook.XmlPage> page;
    @XmlAttribute(name = "id", required = true)
    protected String id;
    @XmlAttribute(name = "author", required = true)
    protected String author;

    /**
     * Gets the value of the permissions property.
     * 
     * @return
     *     possible object is
     *     {@link XmlBook.XmlPermissions }
     *     
     */
    public XmlBook.XmlPermissions getPermissions() {
        return permissions;
    }

    /**
     * Sets the value of the permissions property.
     * 
     * @param value
     *     allowed object is
     *     {@link XmlBook.XmlPermissions }
     *     
     */
    public void setPermissions(XmlBook.XmlPermissions value) {
        this.permissions = value;
    }

    /**
     * Gets the value of the templates property.
     * 
     * @return
     *     possible object is
     *     {@link XmlBook.XmlTemplates }
     *     
     */
    public XmlBook.XmlTemplates getTemplates() {
        return templates;
    }

    /**
     * Sets the value of the templates property.
     * 
     * @param value
     *     allowed object is
     *     {@link XmlBook.XmlTemplates }
     *     
     */
    public void setTemplates(XmlBook.XmlTemplates value) {
        this.templates = value;
    }

    /**
     * Gets the value of the page property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the page property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPage().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link XmlBook.XmlPage }
     * 
     * 
     */
    public List<XmlBook.XmlPage> getPage() {
        if (page == null) {
            page = new ArrayList<XmlBook.XmlPage>();
        }
        return this.page;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the author property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAuthor() {
        return author;
    }

    /**
     * Sets the value of the author property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAuthor(String value) {
        this.author = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="line" maxOccurs="14"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;choice maxOccurs="unbounded"&gt;
     *                   &lt;element name="tpl" maxOccurs="unbounded"&gt;
     *                     &lt;complexType&gt;
     *                       &lt;simpleContent&gt;
     *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
     *                           &lt;attribute name="ref" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *                           &lt;attribute name="arg1" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *                           &lt;attribute name="arg2" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *                           &lt;attribute name="arg3" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *                           &lt;attribute name="arg4" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *                           &lt;attribute name="arg5" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *                           &lt;attribute name="styles" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *                           &lt;attribute name="color" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *                           &lt;attribute name="auto-type" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *                           &lt;attribute name="page" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *                           &lt;attribute name="url" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *                           &lt;attribute name="hover-text" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *                           &lt;attribute name="execute" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *                           &lt;attribute name="open-book" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *                           &lt;attribute name="give-book" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *                         &lt;/extension&gt;
     *                       &lt;/simpleContent&gt;
     *                     &lt;/complexType&gt;
     *                   &lt;/element&gt;
     *                   &lt;element name="obj" maxOccurs="unbounded"&gt;
     *                     &lt;complexType&gt;
     *                       &lt;simpleContent&gt;
     *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
     *                           &lt;attribute name="styles" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *                           &lt;attribute name="color" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *                           &lt;attribute name="auto-type" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *                           &lt;attribute name="page" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *                           &lt;attribute name="url" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *                           &lt;attribute name="hover-text" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *                           &lt;attribute name="execute" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *                           &lt;attribute name="open-book" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *                           &lt;attribute name="give-book" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *                         &lt;/extension&gt;
     *                       &lt;/simpleContent&gt;
     *                     &lt;/complexType&gt;
     *                   &lt;/element&gt;
     *                 &lt;/choice&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *       &lt;attribute name="ref" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "line"
    })
    public static class XmlPage {

        @XmlElement(required = true)
        protected List<XmlBook.XmlPage.XmlLine> line;
        @XmlAttribute(name = "ref")
        protected String ref;

        /**
         * Gets the value of the line property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the line property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getLine().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link XmlBook.XmlPage.XmlLine }
         * 
         * 
         */
        public List<XmlBook.XmlPage.XmlLine> getLine() {
            if (line == null) {
                line = new ArrayList<XmlBook.XmlPage.XmlLine>();
            }
            return this.line;
        }

        /**
         * Gets the value of the ref property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRef() {
            return ref;
        }

        /**
         * Sets the value of the ref property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRef(String value) {
            this.ref = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;choice maxOccurs="unbounded"&gt;
         *         &lt;element name="tpl" maxOccurs="unbounded"&gt;
         *           &lt;complexType&gt;
         *             &lt;simpleContent&gt;
         *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
         *                 &lt;attribute name="ref" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
         *                 &lt;attribute name="arg1" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
         *                 &lt;attribute name="arg2" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
         *                 &lt;attribute name="arg3" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
         *                 &lt;attribute name="arg4" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
         *                 &lt;attribute name="arg5" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
         *                 &lt;attribute name="styles" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
         *                 &lt;attribute name="color" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
         *                 &lt;attribute name="auto-type" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
         *                 &lt;attribute name="page" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
         *                 &lt;attribute name="url" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
         *                 &lt;attribute name="hover-text" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
         *                 &lt;attribute name="execute" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
         *                 &lt;attribute name="open-book" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
         *                 &lt;attribute name="give-book" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
         *               &lt;/extension&gt;
         *             &lt;/simpleContent&gt;
         *           &lt;/complexType&gt;
         *         &lt;/element&gt;
         *         &lt;element name="obj" maxOccurs="unbounded"&gt;
         *           &lt;complexType&gt;
         *             &lt;simpleContent&gt;
         *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
         *                 &lt;attribute name="styles" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
         *                 &lt;attribute name="color" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
         *                 &lt;attribute name="auto-type" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
         *                 &lt;attribute name="page" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
         *                 &lt;attribute name="url" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
         *                 &lt;attribute name="hover-text" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
         *                 &lt;attribute name="execute" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
         *                 &lt;attribute name="open-book" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
         *                 &lt;attribute name="give-book" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
         *               &lt;/extension&gt;
         *             &lt;/simpleContent&gt;
         *           &lt;/complexType&gt;
         *         &lt;/element&gt;
         *       &lt;/choice&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "content"
        })
        public static class XmlLine {

            @XmlElementRefs({
                @XmlElementRef(name = "tpl", type = JAXBElement.class, required = false),
                @XmlElementRef(name = "obj", type = JAXBElement.class, required = false)
            })
            @XmlMixed
            protected List<Serializable> content;

            /**
             * Gets the value of the content property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the content property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getContent().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link JAXBElement }{@code <}{@link XmlBook.XmlPage.XmlLine.XmlTpl }{@code >}
             * {@link JAXBElement }{@code <}{@link XmlBook.XmlPage.XmlLine.XmlObj }{@code >}
             * {@link String }
             * 
             * 
             */
            public List<Serializable> getContent() {
                if (content == null) {
                    content = new ArrayList<Serializable>();
                }
                return this.content;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType&gt;
             *   &lt;simpleContent&gt;
             *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
             *       &lt;attribute name="styles" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
             *       &lt;attribute name="color" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
             *       &lt;attribute name="auto-type" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
             *       &lt;attribute name="page" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
             *       &lt;attribute name="url" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
             *       &lt;attribute name="hover-text" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
             *       &lt;attribute name="execute" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
             *       &lt;attribute name="open-book" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
             *       &lt;attribute name="give-book" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
             *     &lt;/extension&gt;
             *   &lt;/simpleContent&gt;
             * &lt;/complexType&gt;
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "value"
            })
            public static class XmlObj {

                @XmlValue
                protected String value;
                @XmlAttribute(name = "styles")
                protected String styles;
                @XmlAttribute(name = "color")
                protected String color;
                @XmlAttribute(name = "auto-type")
                protected String autoType;
                @XmlAttribute(name = "page")
                protected String page;
                @XmlAttribute(name = "url")
                protected String url;
                @XmlAttribute(name = "hover-text")
                protected String hoverText;
                @XmlAttribute(name = "execute")
                protected String execute;
                @XmlAttribute(name = "open-book")
                protected String openBook;
                @XmlAttribute(name = "give-book")
                protected String giveBook;

                /**
                 * Gets the value of the value property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getValue() {
                    return value;
                }

                /**
                 * Sets the value of the value property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setValue(String value) {
                    this.value = value;
                }

                /**
                 * Gets the value of the styles property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getStyles() {
                    return styles;
                }

                /**
                 * Sets the value of the styles property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setStyles(String value) {
                    this.styles = value;
                }

                /**
                 * Gets the value of the color property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getColor() {
                    return color;
                }

                /**
                 * Sets the value of the color property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setColor(String value) {
                    this.color = value;
                }

                /**
                 * Gets the value of the autoType property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getAutoType() {
                    return autoType;
                }

                /**
                 * Sets the value of the autoType property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setAutoType(String value) {
                    this.autoType = value;
                }

                /**
                 * Gets the value of the page property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getPage() {
                    return page;
                }

                /**
                 * Sets the value of the page property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setPage(String value) {
                    this.page = value;
                }

                /**
                 * Gets the value of the url property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getUrl() {
                    return url;
                }

                /**
                 * Sets the value of the url property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setUrl(String value) {
                    this.url = value;
                }

                /**
                 * Gets the value of the hoverText property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getHoverText() {
                    return hoverText;
                }

                /**
                 * Sets the value of the hoverText property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setHoverText(String value) {
                    this.hoverText = value;
                }

                /**
                 * Gets the value of the execute property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getExecute() {
                    return execute;
                }

                /**
                 * Sets the value of the execute property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setExecute(String value) {
                    this.execute = value;
                }

                /**
                 * Gets the value of the openBook property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getOpenBook() {
                    return openBook;
                }

                /**
                 * Sets the value of the openBook property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setOpenBook(String value) {
                    this.openBook = value;
                }

                /**
                 * Gets the value of the giveBook property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getGiveBook() {
                    return giveBook;
                }

                /**
                 * Sets the value of the giveBook property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setGiveBook(String value) {
                    this.giveBook = value;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType&gt;
             *   &lt;simpleContent&gt;
             *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
             *       &lt;attribute name="ref" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
             *       &lt;attribute name="arg1" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
             *       &lt;attribute name="arg2" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
             *       &lt;attribute name="arg3" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
             *       &lt;attribute name="arg4" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
             *       &lt;attribute name="arg5" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
             *       &lt;attribute name="styles" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
             *       &lt;attribute name="color" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
             *       &lt;attribute name="auto-type" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
             *       &lt;attribute name="page" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
             *       &lt;attribute name="url" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
             *       &lt;attribute name="hover-text" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
             *       &lt;attribute name="execute" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
             *       &lt;attribute name="open-book" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
             *       &lt;attribute name="give-book" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
             *     &lt;/extension&gt;
             *   &lt;/simpleContent&gt;
             * &lt;/complexType&gt;
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "value"
            })
            public static class XmlTpl {

                @XmlValue
                protected String value;
                @XmlAttribute(name = "ref", required = true)
                protected String ref;
                @XmlAttribute(name = "arg1")
                protected String arg1;
                @XmlAttribute(name = "arg2")
                protected String arg2;
                @XmlAttribute(name = "arg3")
                protected String arg3;
                @XmlAttribute(name = "arg4")
                protected String arg4;
                @XmlAttribute(name = "arg5")
                protected String arg5;
                @XmlAttribute(name = "styles")
                protected String styles;
                @XmlAttribute(name = "color")
                protected String color;
                @XmlAttribute(name = "auto-type")
                protected String autoType;
                @XmlAttribute(name = "page")
                protected String page;
                @XmlAttribute(name = "url")
                protected String url;
                @XmlAttribute(name = "hover-text")
                protected String hoverText;
                @XmlAttribute(name = "execute")
                protected String execute;
                @XmlAttribute(name = "open-book")
                protected String openBook;
                @XmlAttribute(name = "give-book")
                protected String giveBook;

                /**
                 * Gets the value of the value property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getValue() {
                    return value;
                }

                /**
                 * Sets the value of the value property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setValue(String value) {
                    this.value = value;
                }

                /**
                 * Gets the value of the ref property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getRef() {
                    return ref;
                }

                /**
                 * Sets the value of the ref property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setRef(String value) {
                    this.ref = value;
                }

                /**
                 * Gets the value of the arg1 property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getArg1() {
                    return arg1;
                }

                /**
                 * Sets the value of the arg1 property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setArg1(String value) {
                    this.arg1 = value;
                }

                /**
                 * Gets the value of the arg2 property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getArg2() {
                    return arg2;
                }

                /**
                 * Sets the value of the arg2 property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setArg2(String value) {
                    this.arg2 = value;
                }

                /**
                 * Gets the value of the arg3 property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getArg3() {
                    return arg3;
                }

                /**
                 * Sets the value of the arg3 property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setArg3(String value) {
                    this.arg3 = value;
                }

                /**
                 * Gets the value of the arg4 property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getArg4() {
                    return arg4;
                }

                /**
                 * Sets the value of the arg4 property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setArg4(String value) {
                    this.arg4 = value;
                }

                /**
                 * Gets the value of the arg5 property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getArg5() {
                    return arg5;
                }

                /**
                 * Sets the value of the arg5 property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setArg5(String value) {
                    this.arg5 = value;
                }

                /**
                 * Gets the value of the styles property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getStyles() {
                    return styles;
                }

                /**
                 * Sets the value of the styles property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setStyles(String value) {
                    this.styles = value;
                }

                /**
                 * Gets the value of the color property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getColor() {
                    return color;
                }

                /**
                 * Sets the value of the color property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setColor(String value) {
                    this.color = value;
                }

                /**
                 * Gets the value of the autoType property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getAutoType() {
                    return autoType;
                }

                /**
                 * Sets the value of the autoType property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setAutoType(String value) {
                    this.autoType = value;
                }

                /**
                 * Gets the value of the page property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getPage() {
                    return page;
                }

                /**
                 * Sets the value of the page property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setPage(String value) {
                    this.page = value;
                }

                /**
                 * Gets the value of the url property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getUrl() {
                    return url;
                }

                /**
                 * Sets the value of the url property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setUrl(String value) {
                    this.url = value;
                }

                /**
                 * Gets the value of the hoverText property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getHoverText() {
                    return hoverText;
                }

                /**
                 * Sets the value of the hoverText property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setHoverText(String value) {
                    this.hoverText = value;
                }

                /**
                 * Gets the value of the execute property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getExecute() {
                    return execute;
                }

                /**
                 * Sets the value of the execute property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setExecute(String value) {
                    this.execute = value;
                }

                /**
                 * Gets the value of the openBook property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getOpenBook() {
                    return openBook;
                }

                /**
                 * Sets the value of the openBook property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setOpenBook(String value) {
                    this.openBook = value;
                }

                /**
                 * Gets the value of the giveBook property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getGiveBook() {
                    return giveBook;
                }

                /**
                 * Sets the value of the giveBook property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setGiveBook(String value) {
                    this.giveBook = value;
                }

            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="give" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *         &lt;element name="open" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *         &lt;element name="giveremote" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *         &lt;element name="openremote" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "give",
        "open",
        "giveremote",
        "openremote"
    })
    public static class XmlPermissions {

        protected String give;
        protected String open;
        protected String giveremote;
        protected String openremote;

        /**
         * Gets the value of the give property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getGive() {
            return give;
        }

        /**
         * Sets the value of the give property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setGive(String value) {
            this.give = value;
        }

        /**
         * Gets the value of the open property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getOpen() {
            return open;
        }

        /**
         * Sets the value of the open property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setOpen(String value) {
            this.open = value;
        }

        /**
         * Gets the value of the giveremote property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getGiveremote() {
            return giveremote;
        }

        /**
         * Sets the value of the giveremote property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setGiveremote(String value) {
            this.giveremote = value;
        }

        /**
         * Gets the value of the openremote property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getOpenremote() {
            return openremote;
        }

        /**
         * Sets the value of the openremote property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setOpenremote(String value) {
            this.openremote = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="template" type="{}template" maxOccurs="unbounded"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "template"
    })
    public static class XmlTemplates {

        @XmlElement(required = true)
        protected List<XmlTemplate> template;

        /**
         * Gets the value of the template property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the template property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getTemplate().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link XmlTemplate }
         * 
         * 
         */
        public List<XmlTemplate> getTemplate() {
            if (template == null) {
                template = new ArrayList<XmlTemplate>();
            }
            return this.template;
        }

    }

}
